apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elson-test-local

resources:
- ../base

commonLabels:
  environment: local
  app.kubernetes.io/environment: local

patches:
- target:
    kind: Deployment
    name: elson-frontend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi
- target:
    kind: Deployment
    name: elson-backend
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 512Mi

configMapGenerator:
- name: elson-config
  behavior: merge
  literals:
  - ENVIRONMENT=local
  - LOG_LEVEL=DEBUG
  - API_URL=http://localhost:8000
