# infrastructure/kubernetes/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elson-test-staging

resources:
- ../base

commonLabels:
  environment: staging
  app.kubernetes.io/environment: staging

patches:
- target:
    kind: Deployment
    name: elson-frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
- target:
    kind: Deployment
    name: elson-backend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

configMapGenerator:
- name: elson-config
  behavior: merge
  literals:
  - ENVIRONMENT=staging
  - LOG_LEVEL=INFO
  - API_URL=https://api-staging.elson-trading.local