apiVersion: v1
kind: Service
metadata:
  name: elson-websocket
  namespace: elson
  labels:
    app: elson-websocket
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: elson-websocket
  ports:
  - name: http
    port: 80
    targetPort: 8001
  type: ClusterIP